# SwiftLint Configuration for LaunchNow
# Customize SwiftLint rules for your project

# Paths to include/exclude
included:
  - LaunchNow/

excluded:
  - build/
  - LaunchNow.xcodeproj/
  - .github/

# Disabled rules
disabled_rules:
  - line_length # Allow longer lines for Chinese comments
  - trailing_whitespace
  - todo # Allow TODO comments during development

# Opt-in rules
opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - sorted_first_last
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_imports
  - switch_case_alignment
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Rule configurations
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 3
  statement_level:
    warning: 5

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - x
    - y
    - dx
    - dy
    - id
    - vm
    - ui
    - ok

# Custom rules
custom_rules:
  chinese_comments_allowed:
    name: "Chinese Comments Allowed"
    regex: '\/\/.*[\u4e00-\u9fff]'
    message: "Chinese comments are allowed in this project"
    severity: info