name: Code Quality Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Swift Lint
    runs-on: macos-15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install SwiftLint
      run: |
        brew install swiftlint
        
    - name: Run SwiftLint
      run: |
        swiftlint --reporter github-actions-logging
      continue-on-error: true
      
    - name: Check for Chinese comments
      run: |
        echo "Checking for Chinese characters in comments..."
        grep -r "[\u4e00-\u9fff]" LaunchNow/ --include="*.swift" || echo "No Chinese characters found"
      continue-on-error: true
      
    - name: Count lines of code
      run: |
        echo "=== Code Statistics ==="
        find LaunchNow -name "*.swift" -exec wc -l {} + | tail -1
        echo "Swift files:"
        find LaunchNow -name "*.swift" | wc -l
        echo "Total files:"
        find LaunchNow -type f | wc -l